version: 0.1

phases:
    install:
        commands:
            - echo Install phase started...
    build:
        commands:
            - echo Build started
            - echo Started pre_build phase...
            - ls -al
            - python --version
            - aws --version
    post_build:
        commands:
            - echo Build complete